---
fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    vcsrepo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo'
